services:
  simply_syslog:
    image: ryansteffan/simply_syslog:latest
    container_name: simply_syslog
    restart: always
    environment:
      - UDP_SERVER_ENABLED=true
      - UDP_MAX_MESSAGE_SIZE=1024
      - SELF_LOGGING_LEVEL=6
      - BUFFER_MAX_ITEMS=1024
      - BUFFER_MAX_LIFETIME=15
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      - "6514:6514/tcp"
