version: "3.8"

services:
  simply_syslog:
    image: ryansteffan/simply_syslog:0.8.0-alpha.1
    container_name: simply_syslog
    restart: always
    build:
      context: .
    environment:
      PROTOCOL: "UDP"
      BIND_ADDRESS: "0.0.0.0"
      UDP_PORT: "514"
      TCP_PORT: "5124"
      MAX_TCP_CONNECTIONS: "10"
      BUFFER_LENGTH: "32"
      BUFFER_LIFESPAN: "5"
      MAX_MESSAGE_SIZE: "1024"
      SYSLOG_PATH: "/var/log/syslog.log"
      DEBUG_MESSAGES: "True"
    volumes:
      - simply_syslog_data:/var/log/
    ports:
      - "514:514/udp"
      - "5124:5124/tcp"

volumes:
  simply_syslog_data:
    driver: local
