# https://taskfile.dev

version: '3'

env:
  APP_NAME: simply-syslog
  VERSION: 0.8.0
  CMD_PATH: ./cmd/simplysyslog/main.go
  BUILD_DIR: ./build

tasks:  
  run:
    desc: Run the application using the go run command and the config.json.
    cmds:
      - echo Running the application...
      - sudo go run $CMD_PATH
    vars:
      CGO_ENABLED: 1
    silent: true